version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo ======================================= PRE BUILD ========================================
      - pwd
      - ls -al
      - aws s3 cp s3://team4-properties-bucket/application.properties src/main/resources/application.properties
      - aws s3 cp s3://team4-properties-bucket/api-key.properties src/main/resources/api-key.properties
      - ls -al
      - ls -al src/main/resources/
  build:
    commands:
#      - mvn package
      - mvn package -DskipTests
  post_build:
    commands:
      - mv target/team4-0.0.1.war ROOT.war
artifacts:
  files:
    - ROOT.war
    - .ebextensions/**/*